version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_api_produtos
    environment:
      POSTGRES_DB: produtosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    container_name: api_produtos
    ports:
      - "5100:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=produtosdb;Username=postgres;Password=postgres
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
